namespace Ozakboy.TradeKit.Binance;

/// <summary>
/// 本套件寫進 <see cref="Error.Data"/> 的鍵名。
/// The keys this package writes into <see cref="Error.Data"/>.
/// </summary>
/// <remarks>
/// 對映之後原始的幣安代碼就從 <see cref="Error.Code"/> 消失了,但事後查 log 時它才是能對回官方文件的那一個。
/// 因此原始代碼與原始訊息一律隨錯誤帶走,而不是只留在被吞掉的回應本文裡。
/// After mapping, the original Binance code no longer appears in <see cref="Error.Code"/> — yet it is the one
/// that matches the official documentation when someone reads the log later. The raw code and message therefore
/// travel with the error instead of staying in a response body that has already been discarded.
/// </remarks>
public static class BinanceErrorDataKeys
{
    /// <summary>
    /// 幣安回傳的數值錯誤碼,例如 <c>-2015</c>。以整數字串儲存,可用
    /// <see cref="Error.TryGetInt64(string, out long)"/> 取回。
    /// The numeric Binance code such as <c>-2015</c>, stored as an integer string and readable through
    /// <see cref="Error.TryGetInt64(string, out long)"/>.
    /// </summary>
    public const string ApiCode = "binanceCode";

    /// <summary>
    /// 幣安回傳的原始訊息字串。
    /// The raw message string Binance returned.
    /// </summary>
    public const string ApiMessage = "binanceMessage";

    /// <summary>
    /// 觸發這個錯誤的端點路徑,例如 <c>/fapi/v2/positionRisk</c>。
    /// The endpoint path that produced the error, such as <c>/fapi/v2/positionRisk</c>.
    /// </summary>
    public const string Endpoint = "binanceEndpoint";

    /// <summary>
    /// 觸發這個錯誤的環境名稱。同一個代碼在 Testnet 與主網的意義可能完全不同,少了這一項就分不出來。
    /// The environment the error came from. The same code can mean quite different things on Testnet and on
    /// production, and without this there is no way to tell them apart.
    /// </summary>
    public const string Environment = "binanceEnvironment";

    /// <summary>
    /// 解析失敗時,缺少或無法解析的欄位名稱。
    /// The field that was missing or unparseable when a response could not be read.
    /// </summary>
    public const string Field = "binanceField";

    /// <summary>
    /// 解析失敗時,相關的交易對代碼。
    /// The symbol involved when a response could not be read.
    /// </summary>
    public const string Symbol = "binanceSymbol";

    /// <summary>
    /// 下單失敗時,那張單使用的用戶端訂單編號(冪等識別碼)。
    /// The client order id — the idempotency key — that a failed order submission used.
    /// </summary>
    /// <remarks>
    /// 下單逾時的時候,那張單可能已經進了交易所。這個鍵存在的唯一理由,是讓呼叫端在
    /// <see cref="BinanceFuturesClient.PlaceOrderAsync"/> 回傳失敗之後仍然查得回那張單 ——
    /// 尤其是編號由本套件自動產生、呼叫端手上原本沒有它的情況。少了這一項,自動產生的編號會隨著
    /// 失敗一起消失,那張單就成了一個既查不到也撤不掉的部位。
    /// When a submission times out the order may already be live. This key exists so that a caller can still
    /// find it after <see cref="BinanceFuturesClient.PlaceOrderAsync"/> returns a failure — above all when the
    /// id was generated by this package and the caller never held it. Without it an auto-generated id vanishes
    /// with the failure, and the order becomes a position that can be neither looked up nor cancelled.
    /// </remarks>
    public const string ClientOrderId = "binanceClientOrderId";

    /// <summary>
    /// 條件單送出失敗時,那張單使用的用戶端條件單編號(冪等識別碼)。
    /// The client algo id — the idempotency key — that a failed conditional order submission used.
    /// </summary>
    /// <remarks>
    /// 存在的理由與 <see cref="ClientOrderId"/> 相同,而後果更嚴重:停損送單逾時之後,那張停損可能已經
    /// 掛在交易所。少了這一項,自動產生的編號會隨著失敗一起消失,那張停損就成了一個既查不到也撤不掉、
    /// 卻會在某個價位真的動用部位的東西。
    /// It exists for the same reason as <see cref="ClientOrderId"/>, with worse consequences: after a stop's
    /// submission times out the stop may already be resting at the exchange. Without this key an
    /// auto-generated id vanishes with the failure, leaving a stop that can be neither looked up nor cancelled
    /// and that will nevertheless move the position at some price.
    /// </remarks>
    public const string ClientAlgoId = "binanceClientAlgoId";
}
